name: test
on:
  workflow_dispatch:

jobs:
  collect-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: gardenlinux
      - uses: actions/checkout@v4
        with:
          repository: 'gardenlinux/builder'
          path: builder
      - run: sudo apt-get -y install python3 python3-mako python3-networkx python3-pefile python3-yaml
      - run: |
          python builder/builder/parse_features --feature-dir gardenlinux/features --features kvm,lima,_curl cname_base

      - run: |
          python builder/builder/parse_features --feature-dir gardenlinux/features --features kvm,lima,_curl --version 1312.1 --default-arch arm64 cname

      - run: |
          python builder/builder/parse_features --feature-dir gardenlinux/features --features kvm,lima,_curl --version 1312.1 --default-arch arm64 features

      - run: |
          python builder/builder/parse_features --feature-dir gardenlinux/features --features _curl --version 1312.1 --default-arch arm64 graph
